services:
  aiketing-db:
    image: postgres:15
    container_name: aiketing-db-container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@071995
      - POSTGRES_DB=aiketing_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: aiketing-ollama-container
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    container_name: aiketing-backend-container
    build:
      context: .
      dockerfile: src/Backend/Dockerfile
    ports:
      - "5235:8080" 
    depends_on:
      - aiketing-db
      - ollama
    environment:
      - ConnectionStrings__DefaultConnection=Host=aiketing-db;Port=5432;Database=aiketing_db;Username=postgres;Password=@071995
      - ASPNETCORE_URLS=http://+:8080

  client:
    container_name: aiketing-client-container
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8080

volumes:
  postgres_data:
  ollama_data: